/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/cadastro`; params?: Router.UnknownInputParams; } | { pathname: `/FinalizarCad`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/agenda/Agenda`; params?: Router.UnknownInputParams; } | { pathname: `/cliente/Ai`; params?: Router.UnknownInputParams; } | { pathname: `/cliente/ClienteScreen`; params?: Router.UnknownInputParams; } | { pathname: `/cliente/clientStyles`; params?: Router.UnknownInputParams; } | { pathname: `/cliente/DetalhesCliente`; params?: Router.UnknownInputParams; } | { pathname: `/cliente/DetalhesMapping`; params?: Router.UnknownInputParams; } | { pathname: `/cliente/EditarCliente`; params?: Router.UnknownInputParams; } | { pathname: `/forgotPassword/ForgotPassword`; params?: Router.UnknownInputParams; } | { pathname: `/home/HomeScreen`; params?: Router.UnknownInputParams; } | { pathname: `/home/Mapping`; params?: Router.UnknownInputParams; } | { pathname: `/home/Menus`; params?: Router.UnknownInputParams; } | { pathname: `/home/Profile`; params?: Router.UnknownInputParams; } | { pathname: `/home/styles`; params?: Router.UnknownInputParams; } | { pathname: `/lembretes/Lembretes`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/cadastro`; params?: Router.UnknownOutputParams; } | { pathname: `/FinalizarCad`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/agenda/Agenda`; params?: Router.UnknownOutputParams; } | { pathname: `/cliente/Ai`; params?: Router.UnknownOutputParams; } | { pathname: `/cliente/ClienteScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/cliente/clientStyles`; params?: Router.UnknownOutputParams; } | { pathname: `/cliente/DetalhesCliente`; params?: Router.UnknownOutputParams; } | { pathname: `/cliente/DetalhesMapping`; params?: Router.UnknownOutputParams; } | { pathname: `/cliente/EditarCliente`; params?: Router.UnknownOutputParams; } | { pathname: `/forgotPassword/ForgotPassword`; params?: Router.UnknownOutputParams; } | { pathname: `/home/HomeScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/home/Mapping`; params?: Router.UnknownOutputParams; } | { pathname: `/home/Menus`; params?: Router.UnknownOutputParams; } | { pathname: `/home/Profile`; params?: Router.UnknownOutputParams; } | { pathname: `/home/styles`; params?: Router.UnknownOutputParams; } | { pathname: `/lembretes/Lembretes`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/cadastro${`?${string}` | `#${string}` | ''}` | `/FinalizarCad${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/agenda/Agenda${`?${string}` | `#${string}` | ''}` | `/cliente/Ai${`?${string}` | `#${string}` | ''}` | `/cliente/ClienteScreen${`?${string}` | `#${string}` | ''}` | `/cliente/clientStyles${`?${string}` | `#${string}` | ''}` | `/cliente/DetalhesCliente${`?${string}` | `#${string}` | ''}` | `/cliente/DetalhesMapping${`?${string}` | `#${string}` | ''}` | `/cliente/EditarCliente${`?${string}` | `#${string}` | ''}` | `/forgotPassword/ForgotPassword${`?${string}` | `#${string}` | ''}` | `/home/HomeScreen${`?${string}` | `#${string}` | ''}` | `/home/Mapping${`?${string}` | `#${string}` | ''}` | `/home/Menus${`?${string}` | `#${string}` | ''}` | `/home/Profile${`?${string}` | `#${string}` | ''}` | `/home/styles${`?${string}` | `#${string}` | ''}` | `/lembretes/Lembretes${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/cadastro`; params?: Router.UnknownInputParams; } | { pathname: `/FinalizarCad`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/agenda/Agenda`; params?: Router.UnknownInputParams; } | { pathname: `/cliente/Ai`; params?: Router.UnknownInputParams; } | { pathname: `/cliente/ClienteScreen`; params?: Router.UnknownInputParams; } | { pathname: `/cliente/clientStyles`; params?: Router.UnknownInputParams; } | { pathname: `/cliente/DetalhesCliente`; params?: Router.UnknownInputParams; } | { pathname: `/cliente/DetalhesMapping`; params?: Router.UnknownInputParams; } | { pathname: `/cliente/EditarCliente`; params?: Router.UnknownInputParams; } | { pathname: `/forgotPassword/ForgotPassword`; params?: Router.UnknownInputParams; } | { pathname: `/home/HomeScreen`; params?: Router.UnknownInputParams; } | { pathname: `/home/Mapping`; params?: Router.UnknownInputParams; } | { pathname: `/home/Menus`; params?: Router.UnknownInputParams; } | { pathname: `/home/Profile`; params?: Router.UnknownInputParams; } | { pathname: `/home/styles`; params?: Router.UnknownInputParams; } | { pathname: `/lembretes/Lembretes`; params?: Router.UnknownInputParams; };
    }
  }
}
